services:
  backup-cisco:
    build:
      context: .
    image: backup-cisco:local
    container_name: backup-cisco
    user: "${BACKUP_UID:-1000}:${BACKUP_GID:-1000}"
    volumes:
      - ./project:/ansible/project
      - ./backups:/ansible/backups
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    working_dir: /ansible/project
